[build]
	publish = "public"
	command = "npm run build"

[[redirects]]
  from = "/20201115134137/"
  to = "https://kajiri.dev/markdown-test"
  status = 301
  force = true

[[redirects]]
  from = "/20201107180155/"
  to = "https://kajiri.dev/vue-js-v2-comment"
  status = 301
  force = true

[[redirects]]
  from = "/20201122202639/"
  to = "https://kajiri.dev/i-read-obsidians-best-practices"
  status = 301
  force = true

[[redirects]]
  from = "/20201206200930/"
  to = "https://kajiri.dev/i-am-having-trouble-with-javascript-numeric-determination"
  status = 301
  force = true

[[redirects]]
  from = "/20201206150441/"
  to = "https://kajiri.dev/i-ran-ruby-base64-encode-decode-on-japanese-and-it-failed"
  status = 301
  force = true


