[build]
	publish = "public"
	command = "npm run build"

[[redirects]]
  from = "/20201115134137/"
  to = "https://kajiri.dev/markdown-test"
  status = 301
  force = true

[[redirects]]
  from = "/20201107180155/"
  to = "https://kajiri.dev/vue-js-v2-comment"
  status = 301
  force = true

[[redirects]]
  from = "/20201122202639/"
  to = "https://kajiri.dev/i-read-obsidians-best-practices"
  status = 301
  force = true

[[redirects]]
  from = "/20201206200930/"
  to = "https://kajiri.dev/i-am-having-trouble-with-javascript-numeric-determination"
  status = 301
  force = true

[[redirects]]
  from = "/20201206150441/"
  to = "https://kajiri.dev/i-ran-ruby-base64-encode-decode-on-japanese-and-it-failed"
  status = 301
  force = true

[[redirects]]
  from = "/20201121231214/"
  to = "https://kajiri.dev/v-model-is-syntax-sugar"
  status = 301
  force = true

[[redirects]]
  from = "/20201206181654/"
  to = "https://kajiri.dev/i-bought-a-smart-watch-that-notifies-me-of-slack"
  status = 301
  force = true

[[redirects]]
  from = "/20201205232320/"
  to = "https://kajiri.dev/when-i-tried-to-install-solargraph-in-vscode-the-latest-version-was-included-and-an-error-occurred"
  status = 301
  force = true

[[redirects]]
  from = "/20201229180502/"
  to = "https://kajiri.dev/apple-shortcuts-sample"
  status = 301
  force = true

[[redirects]]
  from = "/20210102063105/"
  to = "https://kajiri.dev/installation-and-usage-of-tig-wsl2"
  status = 301
  force = true

[[redirects]]
  from = "/20210111220019/"
  to = "https://kajiri.dev/checked-cookie-with-same-key-but-different-domain-attribute-js-cookie"
  status = 301
  force = true

[[redirects]]
  from = "/20201205233245/"
  to = "https://kajiri.dev/3-plug-ins-we-are-currently-using-in-obsidian"
  status = 301
  force = true

[[redirects]]
  from = "/20201206155732/"
  to = "https://kajiri.dev/i-was-wondering-about-the-initial-value-of-the-value-generated-by-attraccessor"
  status = 301
  force = true

[[redirects]]
  from = "/20201128200327/"
  to = "https://kajiri.dev/i-ran-an-empty-act-in-react-and-the-error-disappeared"
  status = 301
  force = true

[[redirects]]
  from = "/20201122230750/"
  to = "https://kajiri.dev/when-you-want-to-test-an-element-that-is-visible-in-testcafe"
  status = 301
  force = true

[[redirects]]
  from = "/20201206195934/"
  to = "https://kajiri.dev/it-looks-like-reactcreateelement-handles-arrays-just-fine"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "https://kajiri.dev"
  status = 301
  force = true
