[build]
	publish = "public"
	command = "npm run build"

[[redirects]]
  from = "/20201115134137/"
  to = "https://kajiri.dev/markdown-test"
  status = 301
  force = true

[[redirects]]
  from = "/20201107180155/"
  to = "https://kajiri.dev/vue-js-v2-comment"
  status = 301
  force = true

